### ISSUE TITLE
Sketch won't compile - Arduino IDE 2.3.3

### ISSUE THREAD

**Issue by vrocco** [evildaemond/doorsim#2]
Arduino IDE 2.3.3 - Latest version of all libraries specified. Here are the compilation errors I get:

C:\Users\user\Desktop\doorsim\doorsim.ino: In lambda function:
C:\Users\user\Desktop\doorsim\doorsim.ino:1234:7: error: 'DynamicJsonDocument' was not declared in this scope
 1234 |       DynamicJsonDocument doc(4096);
      |       ^~~~~~~~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1235:7: error: 'JsonArray' was not declared in this scope
 1235 |       JsonArray cards = doc.to<JsonArray>();
      |       ^~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1237:11: error: 'JsonObject' was not declared in this scope
 1237 |           JsonObject card = cards.createNestedObject();
      |           ^~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1238:11: error: 'card' was not declared in this scope
 1238 |           card["bitCount"] = cardDataArray[i].bitCount;
      |           ^~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1247:21: error: 'doc' was not declared in this scope
 1247 |       serializeJson(doc, response);
      |                     ^~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1247:7: error: 'serializeJson' was not declared in this scope
 1247 |       serializeJson(doc, response);
      |       ^~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino: In lambda function:
C:\Users\user\Desktop\doorsim\doorsim.ino:1252:7: error: 'DynamicJsonDocument' was not declared in this scope
 1252 |       DynamicJsonDocument doc(4096);
      |       ^~~~~~~~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1253:7: error: 'JsonArray' was not declared in this scope
 1253 |       JsonArray users = doc.to<JsonArray>();
      |       ^~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1255:11: error: 'JsonObject' was not declared in this scope
 1255 |           JsonObject user = users.createNestedObject();
      |           ^~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1256:11: error: 'user' was not declared in this scope
 1256 |           user["facilityCode"] = credentials[i].facilityCode;
      |           ^~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1261:21: error: 'doc' was not declared in this scope
 1261 |       serializeJson(doc, response);
      |                     ^~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1261:7: error: 'serializeJson' was not declared in this scope
 1261 |       serializeJson(doc, response);
      |       ^~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino: In lambda function:
C:\Users\user\Desktop\doorsim\doorsim.ino:1266:7: error: 'DynamicJsonDocument' was not declared in this scope
 1266 |       DynamicJsonDocument doc(2048);
      |       ^~~~~~~~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1267:7: error: 'doc' was not declared in this scope
 1267 |       doc["mode"] = MODE;
      |       ^~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1279:7: error: 'serializeJson' was not declared in this scope
 1279 |       serializeJson(doc, response);
      |       ^~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino: In function 'void setup()':
C:\Users\user\Desktop\doorsim\doorsim.ino:1283:3: error: 'AsyncCallbackJsonWebHandler' was not declared in this scope; did you mean 'AsyncCallbackWebHandler'?
 1283 |   AsyncCallbackJsonWebHandler* handler = new AsyncCallbackJsonWebHandler("/saveSettings", [](AsyncWebServerRequest *request, JsonVariant &json) {
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   AsyncCallbackWebHandler
C:\Users\user\Desktop\doorsim\doorsim.ino:1283:32: error: 'handler' was not declared in this scope; did you mean 'xt_handler'?
 1283 |   AsyncCallbackJsonWebHandler* handler = new AsyncCallbackJsonWebHandler("/saveSettings", [](AsyncWebServerRequest *request, JsonVariant &json) {
      |                                ^~~~~~~
      |                                xt_handler
C:\Users\user\Desktop\doorsim\doorsim.ino:1283:46: error: expected type-specifier before 'AsyncCallbackJsonWebHandler'
 1283 |   AsyncCallbackJsonWebHandler* handler = new AsyncCallbackJsonWebHandler("/saveSettings", [](AsyncWebServerRequest *request, JsonVariant &json) {
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1303:4: error: expected primary-expression before ')' token
 1303 |   });
      |    ^
C:\Users\user\Desktop\doorsim\doorsim.ino: In lambda function:
C:\Users\user\Desktop\doorsim\doorsim.ino:1347:5: error: 'DynamicJsonDocument' was not declared in this scope
 1347 |     DynamicJsonDocument doc(4096);
      |     ^~~~~~~~~~~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1348:5: error: 'JsonArray' was not declared in this scope
 1348 |     JsonArray users = doc.createNestedArray("users");
      |     ^~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1350:9: error: 'JsonObject' was not declared in this scope
 1350 |         JsonObject user = users.createNestedObject();
      |         ^~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1351:9: error: 'user' was not declared in this scope
 1351 |         user["facilityCode"] = credentials[i].facilityCode;
      |         ^~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1355:14: error: expected ';' before 'cards'
 1355 |     JsonArray cards = doc.createNestedArray("cards");
      |              ^~~~~~
      |              ;
C:\Users\user\Desktop\doorsim\doorsim.ino:1357:9: error: 'JsonObject' was not declared in this scope
 1357 |         JsonObject card = cards.createNestedObject();
      |         ^~~~~~~~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1358:9: error: 'card' was not declared in this scope
 1358 |         card["bitCount"] = cardDataArray[i].bitCount;
      |         ^~~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1365:19: error: 'doc' was not declared in this scope
 1365 |     serializeJson(doc, response);
      |                   ^~~
C:\Users\user\Desktop\doorsim\doorsim.ino:1365:5: error: 'serializeJson' was not declared in this scope
 1365 |     serializeJson(doc, response);
      |     ^~~~~~~~~~~~~

exit status 1

Compilation error: 'DynamicJsonDocument' was not declared in this scope

**Comment by evildaemond** [comment]
Hi there, 

That's odd, can you list all the libraries and versions you installed from your Arduino IDE folder, I've had previous people reach out to find they did not have the right version of ArduinoJSON installed for example, so I want to figure out what may be missing.

**Comment by karlkr** [comment]
Hey, I couldn't figure it out as well. I get the same error with following libraries.

- [ArduinoJSON](https://arduinojson.org/) 7.2.0 ( also tried with 4.0.0, 6.21.5, 5.13.5)
- [AsyncTCP](https://github.com/dvarrel/AsyncTCP)  1.1.4
- [ESP Async Webserver](https://github.com/mathieucarbou/ESPAsyncWebServer) 3.3.21
- [Arduino Luquid Crystal I2C](https://github.com/fdebrabander/Arduino-LiquidCrystal-I2C-library) master from github
- Arduino IDE 1.8.16 on Ubuntu 22.04

**Comment by evildaemond** [comment]
I've just gone and uninstalled then reinstalled the following to verify if it happens on my machine or not (LiquidCrystal would not affect it here) and none have given the same result as yours. The only reason `DynamicJsonDocument` would be erroring is if you had a malformed or improperly installed ArduinoJSON. 

- Arduino JSON - `7.1.0` - <https://arduinojson.org/>
- AsyncTCP - `1.1.4` - <https://github.com/dvarrel/AsyncTCP>
- ESPAsyncWebServer - `1.2.4`- <https://github.com/mathieucarbou/ESPAsyncWebServer>
- ESPAyncTCP - `1.2.4` - <https://github.com/dvarrel/ESPAsyncTCP>

I understand that you couldn't figure it out, but at this stage it's an environment issue.

**Comment by karlkr** [comment]
I got it to compile using ESPAsyncWebServer 1.2.4 from https://github.com/me-no-dev/ESPAsyncWebServer instead the url you listed

**Comment by evildaemond** [comment]
Not an issue, closing with comment and updating readme. 

Thank you for bringing this up, seems like that's what I had on my downloads list but didn't have it in my Arduino IDE list for some reason.

**Comment by nechry** [comment]
Hello, I tried and re-tried to get the right library combination but still not enabled to compile...
Can someone share zipped versions of a working copy?

I got the same error as reported initially in this issue
Compilation error: 'DynamicJsonDocument' was not declared in this scope

I didn't find on [ESPAsyncWebServer](https://github.com/mathieucarbou/ESPAsyncWebServer) repo a version 1.2.4, the oldest is [v2.4.1](https://github.com/mathieucarbou/ESPAsyncWebServer/releases/tag/v2.4.1)

I found this version [ESPAsyncWebSrv](https://github.com/dvarrel/ESPAsyncWebSrv/releases/tag/1.2.4) but it lookm like it's the right one


I just received my PCB today!

thank- for your help

**Comment by evildaemond** [comment]
Hey there @nechry,

The link you're looking for is    
[ESPAsyncWebServer by Me-No-Dev](https://github.com/me-no-dev/ESPAsyncWebServer)

**Comment by nechry** [comment]
ok but this version is 3.6.0 not 1.2.4

I started reworking the code with platformio instead of Arduino. 
but right now I didn't got any reading form the reader, me be the one I bot isn't fully compatble.
Can you also share ref on tested reader?

**Comment by nechry** [comment]
I finally got the doorsim working, but with PlatformIO.
is my refactoring: [https://github.com/nechry/DoorSim](https://github.com/nechry/DoorSim)
thank-you
